import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as React from 'react';
import { styled } from '@mui/material/styles';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';
import CssBaseline from '@mui/material/CssBaseline';
import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Link from '@mui/material/Link';
import Button from '@mui/material/Button';
import Stack from '@mui/material/Stack';
import { grid } from '@mui/system';
import CameraIcon from '@mui/icons-material/Camera';

function Copyright() {
  return (
    <Typography variant="body2" color="text.secondary">
      {'Copyright © '}
      <Link color="inherit" href="https://mui.com/">
        OpenStock
      </Link>{' '}
      {new Date().getFullYear()}
      {'.'}
    </Typography>
  );
}

const Item = styled(Paper)(({ theme }) => ({
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: 'center',
  color: theme.palette.text.secondary,
}));

export default function Home() {
  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        minHeight: '100vh',
      }}
    >
      <CssBaseline />
      {/* <Grid container padding="3%" justifyContent="left">
      <CameraIcon></CameraIcon>
      </Grid> */}
      <Container component="main" sx={{ mt: 8, mb: 2 }} maxWidth="sm">
        <Typography variant="h2" component="h1" gutterBottom>
          OpenStock
        </Typography>
        <Typography variant="h5" component="h2" gutterBottom>
          {'An open source neural network image generator, publishing creations into the public domain.'}
          {/* {'The footer will move as the main element of the page grows.'} */}
        </Typography>
        <Typography variant="body1">Yeilding the power of GPT-3</Typography>
      </Container>
      <Stack direction="row" spacing={1}>
        <Grid container justifyContent="center">
      <Button color="success" alignItems="center"variant="contained">Start generating!</Button>
      </Grid>
      </Stack>
      <Container component="main" sx={{ mt: 8, mb: 2 }} maxWidth="sm">
      <Typography variant="body1" textAlign="center">Or see images in the public domain that have been generously generated by your fellow users!</Typography>
      </Container>
      <Stack direction="row" spacing={1}>
      <Grid container justifyContent="center">
      <Button alignItems="center"variant="contained">See Images</Button>
      </Grid>
    </Stack>
      <Box
        component="footer"
        sx={{
          py: 3,
          px: 2,
          mt: 'auto',
          backgroundColor: (theme) =>
            theme.palette.mode === 'light'
              ? theme.palette.grey[200]
              : theme.palette.grey[800],
        }}
      >
        <Container maxWidth="sm">
          <Typography variant="body1">
            OpenStock
          </Typography>
          <Copyright />
        </Container>
      </Box>
    </Box>
  )
}
